"""init

Revision ID: 2422fd9a9598
Revises: 
Create Date: 2025-12-01 01:06:49.065249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2422fd9a9598'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users_auth',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('second_name', sa.String(), nullable=False),
    sa.Column('group_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hash_password', sa.LargeBinary(), nullable=False),
    sa.Column('email_confirm', sa.Boolean(), nullable=False),
    sa.Column('role_uid', sa.Uuid(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_uid'], ['roles.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_users_auth_email'), 'users_auth', ['email'], unique=False)
    op.create_table('users_event',
    sa.Column('role_uid', sa.Uuid(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_uid'], ['roles.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('events',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users_event.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('addresses',
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('event_uid', sa.Uuid(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_uid'], ['events.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('buildings',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('block', sa.String(), nullable=True),
    sa.Column('auditorium', sa.String(), nullable=True),
    sa.Column('address_uid', sa.Uuid(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['address_uid'], ['addresses.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buildings')
    op.drop_table('addresses')
    op.drop_table('events')
    op.drop_table('users_event')
    op.drop_index(op.f('ix_users_auth_email'), table_name='users_auth')
    op.drop_table('users_auth')
    op.drop_table('roles')
    # ### end Alembic commands ###
