"""cascade update

Revision ID: 70fc8945817a
Revises: af8c661b085f
Create Date: 2025-12-03 23:49:38.147824

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '70fc8945817a'
down_revision: Union[str, Sequence[str], None] = 'af8c661b085f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
