"""add m2m-event-user

Revision ID: af8c661b085f
Revises: 2422fd9a9598
Create Date: 2025-12-02 16:47:59.328464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8c661b085f'
down_revision: Union[str, Sequence[str], None] = '2422fd9a9598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('a_events_users',
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('event_uid', sa.Uuid(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_uid'], ['events.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['users_event.uid'], ),
    sa.PrimaryKeyConstraint('user_uid', 'event_uid', 'uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('a_events_users')
    # ### end Alembic commands ###
