"""add events.image_url

Revision ID: d72d67e8bc46
Revises: 70fc8945817a
Create Date: 2025-12-14 12:36:42.148083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd72d67e8bc46'
down_revision: Union[str, Sequence[str], None] = '70fc8945817a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('image_uid', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'image_uid')
    # ### end Alembic commands ###
